In [99]:
import pandas as pd
import numpy as np

In [100]:
df=pd.read_csv(r'P:\jay\fliprobo\Micro Credit Project\Data file.csv')
df.head()

Unnamed: 0  label       msisdn    aon  daily_decr30  daily_decr90  \
0           1      0  21408I70789  272.0   3055.050000   3065.150000   
1           2      1  76462I70374  712.0  12122.000000  12124.750000   
2           3      1  17943I70372  535.0   1398.000000   1398.000000   
3           4      1  55773I70781  241.0     21.228000     21.228000   
4           5      1  03813I82730  947.0    150.619333    150.619333   

   rental30  rental90  last_rech_date_ma  last_rech_date_da  ...  \
0    220.13    260.13                2.0                0.0  ...   
1   3691.26   3691.26               20.0                0.0  ...   
2    900.13    900.13                3.0                0.0  ...   
3    159.42    159.42               41.0                0.0  ...   
4   1098.90   1098.90                4.0                0.0  ...   

   maxamnt_loans30  medianamnt_loans30  cnt_loans90  amnt_loans90  \
0              6.0                 0.0          2.0            12   
1             12.0                 0.0          1.0            12   
2              6.0                 0.0          1.0             6   
3              6.0                 0.0          2.0            12   
4              6.0                 0.0          7.0            42   

   maxamnt_loans90  medianamnt_loans90  payback30  payback90  pcircle  \
0                6                 0.0  29.000000  29.000000      UPW   
1               12                 0.0   0.000000   0.000000      UPW   
2                6                 0.0   0.000000   0.000000      UPW   
3                6                 0.0   0.000000   0.000000      UPW   
4                6                 0.0   2.333333   2.333333      UPW   

        pdate  
0  2016-07-20  
1  2016-08-10  
2  2016-08-19  
3  2016-06-06  
4  2016-06-22  

[5 rows x 37 columns]

In [101]:
df.shape

(209593, 37)

In [102]:
df.isnull().sum()

Unnamed: 0              0
label                   0
msisdn                  0
aon                     0
daily_decr30            0
daily_decr90            0
rental30                0
rental90                0
last_rech_date_ma       0
last_rech_date_da       0
last_rech_amt_ma        0
cnt_ma_rech30           0
fr_ma_rech30            0
sumamnt_ma_rech30       0
medianamnt_ma_rech30    0
medianmarechprebal30    0
cnt_ma_rech90           0
fr_ma_rech90            0
sumamnt_ma_rech90       0
medianamnt_ma_rech90    0
medianmarechprebal90    0
cnt_da_rech30           0
fr_da_rech30            0
cnt_da_rech90           0
fr_da_rech90            0
cnt_loans30             0
amnt_loans30            0
maxamnt_loans30         0
medianamnt_loans30      0
cnt_loans90             0
amnt_loans90            0
maxamnt_loans90         0
medianamnt_loans90      0
payback30               0
payback90               0
pcircle                 0
pdate                   0
dtype: int64

In [103]:
df.dtypes

Unnamed: 0                int64
label                     int64
msisdn                   object
aon                     float64
daily_decr30            float64
daily_decr90            float64
rental30                float64
rental90                float64
last_rech_date_ma       float64
last_rech_date_da       float64
last_rech_amt_ma          int64
cnt_ma_rech30             int64
fr_ma_rech30            float64
sumamnt_ma_rech30       float64
medianamnt_ma_rech30    float64
medianmarechprebal30    float64
cnt_ma_rech90             int64
fr_ma_rech90              int64
sumamnt_ma_rech90         int64
medianamnt_ma_rech90    float64
medianmarechprebal90    float64
cnt_da_rech30           float64
fr_da_rech30            float64
cnt_da_rech90             int64
fr_da_rech90              int64
cnt_loans30               int64
amnt_loans30              int64
maxamnt_loans30         float64
medianamnt_loans30      float64
cnt_loans90             float64
amnt_loans90              int64
maxamnt_

In [104]:
#removing no relation feature like sr.no, mobileno, date
df.drop(['Unnamed: 0','msisdn','pdate','pcircle'],axis=1,inplace=True)
df.shape

(209593, 33)

In [105]:
#removing outlier with use of zscore
from scipy.stats import zscore
z=np.abs(zscore(df))

In [106]:
print(np.where(z>3))

(array([    21,     22,     22, ..., 209586, 209587, 209587], dtype=int64), array([15, 15, 32, ..., 28, 26, 30], dtype=int64))


In [107]:
dfn=df[(z<3).all(axis=1)]
dfn.shape

(161465, 33)

In [108]:
# divide dependent and independet feature
x=dfn.iloc[:,1:]
y=dfn.iloc[:,0]
print(x.shape,y.shape)

(161465, 32) (161465,)


In [109]:
#scale the data
from sklearn.preprocessing import StandardScaler
sd=StandardScaler()
xn=sd.fit_transform(x)
xn

array([[-0.75398887, -0.1264675 , -0.16967941, ..., -0.15976925,
         6.23836713,  5.20690442],
       [ 0.13222065,  1.47522009,  1.23502373, ..., -0.15976925,
        -0.61935187, -0.6470595 ],
       [-0.22427727, -0.41918737, -0.42817326, ..., -0.15976925,
        -0.61935187, -0.6470595 ],
       ...,
       [ 0.73846853,  1.42595414,  1.20085042, ..., -0.15976925,
         0.32654041,  0.12674032],
       [ 2.18661545,  1.53991477,  1.30473792, ..., -0.15976925,
        -0.61935187,  1.47247916],
       [ 1.88248445,  0.12690544,  0.05819489, ..., -0.15976925,
        -0.61935187, -0.6470595 ]])

In [110]:
xd=pd.DataFrame(xn)
yd=y

In [111]:
#model creation
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xd,yd,test_size=0.3,random_state=42)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(113025, 32) (48440, 32) (113025,) (48440,)


In [41]:
#import best algorithm then select one 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [42]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()
knn=KNeighborsClassifier(n_neighbors=3)
nb=GaussianNB()
a=[lr,dt,knn,nb]

In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [44]:
for i in a:
    print('process of {}'.format(i))
    i.fit(x_train,y_train)
    pred=i.predict(x_test)
    print(accuracy_score(y_test,pred))
    print(confusion_matrix(y_test,pred))
    print(classification_report(y_test,pred)) 

process of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.8663501238645748
[[  638  6017]
 [  457 41328]]
              precision    recall  f1-score   support

           0       0.58      0.10      0.16      6655
           1       0.87      0.99      0.93     41785

    accuracy                           0.87     48440
   macro avg       0.73      0.54      0.55     48440
weighted avg       0.83      0.87      0.82     48440

process of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')
0.8572254335260115
[[ 3484  3171]
 [ 3745 38040]]
              precision    recall  f1-score   support

           0       0.48      0.52      0.50      6655
           1       0.92      0.91      0.92     

In [114]:
#here we can show decision tree works well on 0 as well 1 output,
#others are fail on 0 prediction so decide to use random forest

from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=100,max_depth=50,n_jobs=-1)
rc.fit(x_train,y_train)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=50, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [115]:
rpred=rc.predict(x_test)
print(accuracy_score(y_test,rpred))
print(confusion_matrix(y_test,rpred))
print(classification_report(y_test,rpred))

0.9083608587943848
[[ 3202  3453]
 [  986 40799]]
              precision    recall  f1-score   support

           0       0.76      0.48      0.59      6655
           1       0.92      0.98      0.95     41785

    accuracy                           0.91     48440
   macro avg       0.84      0.73      0.77     48440
weighted avg       0.90      0.91      0.90     48440



In [56]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [57]:
saved_micro_credit=joblib.dump(rc,'micro_credit.pkl')

In [58]:
load_credit_model=joblib.load('micro_credit.pkl')

In [60]:
load_credit_model.predict(x_test)

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)